import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class Java_calculation extends javax.swing.JFrame {
    ArrayList<RecIntegral> arrInteg = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Java_calculation.class.getName());

    /**
     * Creates new form Java_calculation
     */
    public Java_calculation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabelLower = new javax.swing.JLabel();
        jLabelUpper = new javax.swing.JLabel();
        jLabelStep = new javax.swing.JLabel();
        jTextFieldLowerLimit = new javax.swing.JTextField();
        jTextFieldUpperLimit = new javax.swing.JTextField();
        jTextFieldStep = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonCalculate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonFill = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSaveText = new javax.swing.JMenuItem();
        jMenuItemLoadText = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));

        jLabelLower.setText("Lower Limit");

        jLabelUpper.setText("Upper Limit");

        jLabelStep.setText("Step");

        jTextFieldLowerLimit.setColumns(10);
        jTextFieldLowerLimit.addActionListener(this::jTextFieldLowerLimitActionPerformed);

        jTextFieldUpperLimit.setColumns(10);
        jTextFieldUpperLimit.addActionListener(this::jTextFieldUpperLimitActionPerformed);

        jTextFieldStep.setColumns(10);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabelLower))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jTextFieldLowerLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabelUpper))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextFieldUpperLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabelStep)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextFieldStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLower)
                    .addComponent(jLabelUpper)
                    .addComponent(jLabelStep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLowerLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUpperLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions"));

        jButtonAdd.setText("Add Item");
        jButtonAdd.addActionListener(this::jButtonAddActionPerformed);

        jButtonDelete.setText("Delete Item");
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        jButtonCalculate.setText("Calculate");
        jButtonCalculate.addActionListener(this::jButtonCalculateActionPerformed);

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lower Limit", "Upper Limit", "Step", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jTable1.setIntercellSpacing(new java.awt.Dimension(1, 1));
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);

        jButtonFill.setText("Fill from collection");
        jButtonFill.addActionListener(this::jButtonFillActionPerformed);

        jButtonClear.setText("Clear table");
        jButtonClear.addActionListener(this::jButtonClearActionPerformed);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jButtonAdd)
                .addGap(99, 99, 99)
                .addComponent(jButtonDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCalculate)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonClear)
                .addGap(112, 112, 112)
                .addComponent(jButtonFill)
                .addGap(91, 91, 91))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonCalculate))
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFill)
                    .addComponent(jButtonClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        jMenu1.setText("File");

        jMenuItemSaveText.setText("Save the text");
        jMenuItemSaveText.addActionListener(this::jMenuItemSaveTextActionPerformed);
        jMenu1.add(jMenuItemSaveText);

        jMenuItemLoadText.setText("Load the text");
        jMenuItemLoadText.addActionListener(this::jMenuItemLoadTextActionPerformed);
        jMenu1.add(jMenuItemLoadText);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
         DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
         int rowNum = jTable1.getSelectedRow();

         if (rowNum == -1) {
             JOptionPane.showMessageDialog(null, "You need to select a row");
         } else {
             tModel.removeRow(rowNum);
             arrInteg.remove(rowNum);

        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculateActionPerformed
       
    int rowNum = jTable1.getSelectedRow();

    if (rowNum == -1) {
        JOptionPane.showMessageDialog(null, "You need to select a row");
    } else {
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();

        double upperLim;
        double lowLim;
        double step;
        double result;

        try {
            lowLim   = Double.parseDouble(tModel.getValueAt(rowNum, 0).toString());
            upperLim = Double.parseDouble(tModel.getValueAt(rowNum, 1).toString());
            step     = Double.parseDouble(tModel.getValueAt(rowNum, 2).toString());

            if (step == 0) {
                throw new IllegalArgumentException("Step cannot be 0 (division by zero)");
            }

            RecIntegral rec = new RecIntegral(lowLim, upperLim, step);
            result = rec.CalcIntegral(rec.getLowLim(), rec.getUpperLim(), rec.getStep());
            rec.setResult(result);

            tModel.setValueAt(rec.getResult(), rowNum, 3);
            arrInteg.set(rowNum, rec);
            
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this,
                    e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        } catch (InvalidRangeException exe) {
            JOptionPane.showMessageDialog(this,
                    exe.getMessage() + "Your data: " + exe.getErrVal(),
                    "Input error", JOptionPane.WARNING_MESSAGE);
        }
    }



    }//GEN-LAST:event_jButtonCalculateActionPerformed

    private void jTextFieldUpperLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUpperLimitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUpperLimitActionPerformed

    private void jTextFieldLowerLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLowerLimitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLowerLimitActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
     
    double lowLim;
    double upperLim;
    double step;

    try {
        lowLim   = Double.parseDouble(jTextFieldLowerLimit.getText());
        upperLim = Double.parseDouble(jTextFieldUpperLimit.getText());
        step     = Double.parseDouble(jTextFieldStep.getText());

        RecIntegral rec = new RecIntegral(lowLim, upperLim, step);
        arrInteg.add(rec);

        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        tModel.addRow(new Object[]{rec.getLowLim(), rec.getUpperLim(), rec.getStep()});

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this,
                "Enter the correct numbers (the decimal separator is a dot)",
                "Input error", JOptionPane.ERROR_MESSAGE);
        
     } catch (InvalidRangeException exe) {
        JOptionPane.showMessageDialog(this,
                exe.getMessage() + "Your data: " + exe.getErrVal(),
                "Input error", JOptionPane.WARNING_MESSAGE);
  
        
    } finally {
        jTextFieldLowerLimit.setText("");
        jTextFieldUpperLimit.setText("");
        jTextFieldStep.setText("");
    }

    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFillActionPerformed
        // jButtonFillActionPerformed
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        tModel.setNumRows(0);

        for (RecIntegral item : arrInteg) {
            tModel.addRow(new Object[] {
                item.getLowLim(),
                item.getUpperLim(),
                item.getStep(),
                item.getResult()
            });
        }
    }//GEN-LAST:event_jButtonFillActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // jButtonClearActionPerformed
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        tModel.setNumRows(0);
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jMenuItemSaveTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveTextActionPerformed
                JFileChooser f = new JFileChooser();
        FileNameExtensionFilter filter =
                new FileNameExtensionFilter("Text file (*.txt)", "txt");
        f.setFileFilter(filter);

        if (f.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;   // l-user dar Cancel
        }

        File file = f.getSelectedFile();

        if (!file.getPath().endsWith(".txt")) {
            file = new File(file.getPath() + ".txt");
        }

        try (FileWriter writer = new FileWriter(file, false)) {
            for (RecIntegral o : arrInteg) {
                writer.write(o.getLowLim() + " " +
                             o.getUpperLim() + " " +
                             o.getStep() + " " +
                             o.getResult() + "\n");
            }
            writer.flush();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_jMenuItemSaveTextActionPerformed

    private void jMenuItemLoadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoadTextActionPerformed
                JFileChooser f = new JFileChooser();
        FileNameExtensionFilter filter =
                new FileNameExtensionFilter("Text file (*.txt)", "txt");
        f.setFileFilter(filter);

        if (f.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;   // l-user dar Cancel
        }

        File file = f.getSelectedFile();

        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            arrInteg.clear();
            String temp;
            while ((temp = reader.readLine()) != null) {
                if (temp.trim().isEmpty()) {
                    continue;   // ster khawi
                }
                String[] part = temp.trim().split(" ");
                arrInteg.add(new RecIntegral(
                        Double.parseDouble(part[0]),
                        Double.parseDouble(part[1]),
                        Double.parseDouble(part[2]),
                        Double.parseDouble(part[3])
                ));
            }

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            for (RecIntegral obj : arrInteg) {
                model.addRow(new Object[]{
                    obj.getLowLim(),
                    obj.getUpperLim(),
                    obj.getStep(),
                    obj.getResult()
                });
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex);
        } catch (InvalidRangeException exe) {
            JOptionPane.showMessageDialog(this,
                    exe.getMessage() + "Your data: " + exe.getErrVal(),
                    "Input error", JOptionPane.WARNING_MESSAGE);
        } catch (NumberFormatException | ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(this,
                    "The file format is incorrect",
                    "Input error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemLoadTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Java_calculation().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCalculate;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonFill;
    private javax.swing.JLabel jLabelLower;
    private javax.swing.JLabel jLabelStep;
    private javax.swing.JLabel jLabelUpper;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemLoadText;
    private javax.swing.JMenuItem jMenuItemSaveText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldLowerLimit;
    private javax.swing.JTextField jTextFieldStep;
    private javax.swing.JTextField jTextFieldUpperLimit;
    // End of variables declaration//GEN-END:variables
}
